from .common import ONCO_BASE

_AUDITORIA_BASE = ONCO_BASE + r"""
, CONTAS AS (
    SELECT
        C.CD_REG_AMB,
        MAX(C.CD_ATENDIMENTO) AS CD_ATENDIMENTO,
        MAX(RA.CD_REMESSA) AS CD_REMESSA,
        MAX(NVL(RA.VL_TOTAL_CONTA,0)) AS VL_FATURADO,
        MAX(RF.SN_PAGA) AS SN_PAGA,
        MAX(A.CD_PACIENTE) AS CD_PACIENTE,
        MAX(P.NM_PACIENTE) AS NM_PACIENTE
    FROM CONTAS_ONCO C
    JOIN DBAMV.REG_AMB RA ON RA.CD_REG_AMB = C.CD_REG_AMB
    JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = C.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
    LEFT JOIN DBAMV.REMESSA_FATURA RF ON RF.CD_REMESSA = RA.CD_REMESSA
    GROUP BY C.CD_REG_AMB
),
NOTA AS (
    SELECT INF.CD_REG_AMB, COUNT(DISTINCT INF.CD_ITFAT_NF) AS QT_ITENS_NOTA
    FROM DBAMV.ITFAT_NOTA_FISCAL INF
    JOIN (SELECT DISTINCT CD_REG_AMB FROM CONTAS) C ON C.CD_REG_AMB = INF.CD_REG_AMB
    GROUP BY INF.CD_REG_AMB
),
RECEB AS (
    SELECT
        INF.CD_REG_AMB,
        COUNT(DISTINCT R.CD_RECCON_REC) AS QT_EVENTOS_RECEBIMENTO,
        MIN(R.DT_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
        MAX(R.DT_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA_RECEBIMENTO
    FROM DBAMV.ITFAT_NOTA_FISCAL INF
    JOIN (SELECT DISTINCT CD_REG_AMB FROM CONTAS) C ON C.CD_REG_AMB = INF.CD_REG_AMB
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB
),
BASE AS (
    SELECT
        C.*,
        NVL(N.QT_ITENS_NOTA,0) AS QT_ITENS_NOTA,
        NVL(R.QT_EVENTOS_RECEBIMENTO,0) AS QT_EVENTOS_RECEBIMENTO,
        R.PRIMEIRO_RECEBIMENTO,
        R.ULTIMO_RECEBIMENTO,
        NVL(R.VL_RECEBIDO_FINANCEIRO,0) AS VL_RECEBIDO_FINANCEIRO,
        NVL(R.VL_RECEBIDO_BASE,0) AS VL_RECEBIDO_BASE,
        NVL(R.VL_GLOSA_RECEBIMENTO,0) AS VL_GLOSA_RECEBIMENTO,
        GREATEST(C.VL_FATURADO - NVL(R.VL_RECEBIDO_BASE,0),0) AS VL_SALDO_ESTIMADO,
        LEAST(
          GREATEST(C.VL_FATURADO - NVL(R.VL_RECEBIDO_BASE,0),0),
          NVL(R.VL_GLOSA_RECEBIMENTO,0)
        ) AS VL_SALDO_GLOSADO,
        GREATEST(
          C.VL_FATURADO - NVL(R.VL_RECEBIDO_BASE,0) - NVL(R.VL_GLOSA_RECEBIMENTO,0),
          0
        ) AS VL_SALDO_FINANCEIRO_ABERTO
    FROM CONTAS C
    LEFT JOIN NOTA N ON N.CD_REG_AMB = C.CD_REG_AMB
    LEFT JOIN RECEB R ON R.CD_REG_AMB = C.CD_REG_AMB
)
"""

AUDITORIA_RESUMO = _AUDITORIA_BASE + r"""
SELECT
    COUNT(*) AS QT_CONTAS,
    SUM(CASE WHEN QT_ITENS_NOTA = 0 THEN 1 ELSE 0 END) AS QT_SEM_NOTA,
    SUM(CASE WHEN QT_EVENTOS_RECEBIMENTO = 0 THEN 1 ELSE 0 END) AS QT_SEM_RECEBIMENTO,
    COUNT(DISTINCT CASE WHEN SN_PAGA='S' AND QT_EVENTOS_RECEBIMENTO=0 THEN CD_REMESSA END) AS QT_REMESSA_PAGA_SEM_RECEBIMENTO,
    SUM(CASE WHEN VL_RECEBIDO_BASE > VL_FATURADO + 0.01 THEN 1 ELSE 0 END) AS QT_RECEB_MAIOR_FATURADO,
    SUM(CASE
          WHEN VL_RECEBIDO_BASE > 0
           AND VL_SALDO_FINANCEIRO_ABERTO > 0.01
          THEN 1 ELSE 0 END) AS QT_PARCIALMENTE_RECEBIDA,
    SUM(CASE
          WHEN VL_RECEBIDO_BASE > 0
           AND VL_SALDO_ESTIMADO > 0.01
           AND VL_SALDO_FINANCEIRO_ABERTO <= 0.01
           AND VL_GLOSA_RECEBIMENTO > 0.01
          THEN 1 ELSE 0 END) AS QT_RECEBIDA_COM_GLOSA,
    SUM(CASE WHEN VL_SALDO_ESTIMADO <= 0.01 AND VL_RECEBIDO_BASE > 0 THEN 1 ELSE 0 END) AS QT_RECEBIDAS,
    SUM(CASE WHEN QT_EVENTOS_RECEBIMENTO > 1 THEN 1 ELSE 0 END) AS QT_MULTIPLOS_RECEBIMENTOS,
    SUM(VL_SALDO_ESTIMADO) AS VL_SALDO_ESTIMADO,
    SUM(VL_SALDO_GLOSADO) AS VL_SALDO_GLOSADO,
    SUM(VL_SALDO_FINANCEIRO_ABERTO) AS VL_SALDO_FINANCEIRO_ABERTO
FROM BASE
"""

AUDITORIA_DETALHE = _AUDITORIA_BASE + r"""
SELECT *
FROM (
    SELECT
        CASE
          WHEN QT_ITENS_NOTA = 0 THEN 'SEM_NOTA_FISCAL'
          WHEN SN_PAGA='S' AND QT_EVENTOS_RECEBIMENTO=0 THEN 'REMESSA_PAGA_SEM_RECEBIMENTO'
          WHEN VL_RECEBIDO_BASE > VL_FATURADO + 0.01 THEN 'RECEBIMENTO_MAIOR_QUE_FATURADO'
          WHEN QT_EVENTOS_RECEBIMENTO = 0 THEN 'SEM_RECEBIMENTO'
          WHEN VL_RECEBIDO_BASE > 0
           AND VL_SALDO_ESTIMADO > 0.01
           AND VL_SALDO_FINANCEIRO_ABERTO <= 0.01
           AND VL_GLOSA_RECEBIMENTO > 0.01 THEN 'RECEBIDA_COM_GLOSA'
          WHEN VL_RECEBIDO_BASE > 0 AND VL_SALDO_FINANCEIRO_ABERTO > 0.01 THEN 'RECEBIMENTO_PARCIAL'
          WHEN QT_EVENTOS_RECEBIMENTO > 1 THEN 'MULTIPLOS_RECEBIMENTOS'
          ELSE 'OK'
        END AS TIPO,
        CD_PACIENTE,
        NM_PACIENTE,
        CD_ATENDIMENTO,
        CD_REG_AMB,
        CD_REMESSA,
        SN_PAGA,
        QT_ITENS_NOTA,
        QT_EVENTOS_RECEBIMENTO,
        PRIMEIRO_RECEBIMENTO,
        ULTIMO_RECEBIMENTO,
        VL_FATURADO,
        VL_RECEBIDO_FINANCEIRO,
        VL_RECEBIDO_BASE,
        VL_GLOSA_RECEBIMENTO,
        VL_SALDO_ESTIMADO,
        VL_SALDO_GLOSADO,
        VL_SALDO_FINANCEIRO_ABERTO
    FROM BASE
)
WHERE TIPO <> 'OK'
ORDER BY
    CASE TIPO
      WHEN 'RECEBIMENTO_MAIOR_QUE_FATURADO' THEN 1
      WHEN 'REMESSA_PAGA_SEM_RECEBIMENTO' THEN 2
      WHEN 'SEM_NOTA_FISCAL' THEN 3
      WHEN 'SEM_RECEBIMENTO' THEN 4
      WHEN 'RECEBIMENTO_PARCIAL' THEN 5
      WHEN 'RECEBIDA_COM_GLOSA' THEN 6
      ELSE 7
    END,
    VL_SALDO_FINANCEIRO_ABERTO DESC,
    VL_SALDO_GLOSADO DESC,
    CD_REG_AMB
"""
