ONCO_BASE = """
WITH ATEND_ONCO AS (
    SELECT DISTINCT AO.CD_ATENDIMENTO
    FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
    WHERE AO.CD_CONVENIO = 11
),
CONTAS_ONCO AS (
    SELECT
           IRA.CD_REG_AMB,
           IRA.CD_ATENDIMENTO,
           MIN(IRA.DT_PRODUCAO) AS DT_PRIMEIRA_PRODUCAO,
           MAX(IRA.DT_PRODUCAO) AS DT_ULTIMA_PRODUCAO
    FROM DBAMV.ITREG_AMB IRA
    JOIN ATEND_ONCO AO
      ON AO.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
    WHERE IRA.CD_CONVENIO = 11
      AND IRA.DT_PRODUCAO >= :data_inicio
      AND IRA.DT_PRODUCAO < :data_fim + 1
    GROUP BY IRA.CD_REG_AMB, IRA.CD_ATENDIMENTO
)
"""
