from .common import ONCO_BASE

# Detalhes do coorte assistencial selecionado por DT_PRODUCAO.
# Recebimentos sao acumulados por conta (todas as datas), usando a cadeia financeira validada.
_DETALHES_BASE = ONCO_BASE + r"""
, GLOSA AS (
    SELECT
        G.CD_REG_AMB,
        COUNT(DISTINCT G.CD_GLOSAS) AS QT_EVENTOS_GLOSA,
        SUM(NVL(G.VL_GLOSA,0)) AS VL_GLOSA_BRUTA,
        SUM(CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN NVL(G.VL_GLOSA,0) ELSE 0 END) AS VL_GLOSA_REVERTIDA,
        SUM(CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN 0 ELSE NVL(G.VL_GLOSA,0) END) AS VL_GLOSA_LIQUIDA,
        SUM(NVL(G.VL_REAPRESENTADO,0)) AS VL_REAPRESENTADO,
        SUM(NVL(G.VL_RECEBIDO,0)) AS VL_RECEBIDO_GLOSA,
        SUM(NVL(G.VL_RECURSO_REPASSADO,0)) AS VL_RECURSO_REPASSADO
    FROM DBAMV.GLOSAS G
    JOIN (SELECT DISTINCT CD_REG_AMB FROM CONTAS_ONCO) C ON C.CD_REG_AMB = G.CD_REG_AMB
    GROUP BY G.CD_REG_AMB
),
RECEB_CONTA AS (
    SELECT
        INF.CD_REG_AMB,
        COUNT(DISTINCT R.CD_RECCON_REC) AS QT_EVENTOS_RECEBIMENTO,
        MIN(R.DT_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
        MAX(R.DT_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(V.VL_ACRESCIMO,0)) AS VL_ACRESCIMO_RECEBIMENTO,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA_RECEBIMENTO
    FROM DBAMV.ITFAT_NOTA_FISCAL INF
    JOIN (SELECT DISTINCT CD_REG_AMB FROM CONTAS_ONCO) C ON C.CD_REG_AMB = INF.CD_REG_AMB
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB
),
NOTA_CONTA AS (
    SELECT
        INF.CD_REG_AMB,
        COUNT(DISTINCT INF.CD_NOTA_FISCAL) AS QT_NOTAS_FISCAIS,
        COUNT(DISTINCT INF.CD_ITFAT_NF) AS QT_ITENS_NOTA
    FROM DBAMV.ITFAT_NOTA_FISCAL INF
    JOIN (SELECT DISTINCT CD_REG_AMB FROM CONTAS_ONCO) C ON C.CD_REG_AMB = INF.CD_REG_AMB
    GROUP BY INF.CD_REG_AMB
)
"""

_ATENDIMENTOS_SELECT = r"""
SELECT
    P.CD_PACIENTE,
    P.NM_PACIENTE,
    C.CD_ATENDIMENTO,
    A.DT_ATENDIMENTO,
    C.CD_REG_AMB,
    C.DT_PRIMEIRA_PRODUCAO,
    C.DT_ULTIMA_PRODUCAO,
    RA.DT_LANCAMENTO,
    RA.CD_REMESSA,
    CAST(NULL AS DATE) AS DT_REMESSA,
    RF.NR_REMESSA_CONVENIO,
    RF.DT_FECHAMENTO,
    RF.DT_ENTREGA_DA_FATURA,
    RF.SN_PAGA,
    NVL(RA.VL_TOTAL_CONTA,0) AS VL_FATURADO,
    NVL(G.VL_GLOSA_BRUTA,0) AS VL_GLOSA_BRUTA,
    NVL(G.VL_GLOSA_REVERTIDA,0) AS VL_GLOSA_REVERTIDA,
    NVL(G.VL_GLOSA_LIQUIDA,0) AS VL_GLOSA_LIQUIDA,
    NVL(G.VL_REAPRESENTADO,0) AS VL_REAPRESENTADO,
    NVL(G.VL_RECEBIDO_GLOSA,0) AS VL_RECEBIDO_GLOSA,
    NVL(G.VL_RECURSO_REPASSADO,0) AS VL_RECURSO_REPASSADO,
    NVL(RA.VL_TOTAL_CONTA,0) - NVL(G.VL_GLOSA_LIQUIDA,0) AS VL_POS_GLOSA,
    NVL(G.QT_EVENTOS_GLOSA,0) AS QT_EVENTOS_GLOSA,
    NVL(N.QT_NOTAS_FISCAIS,0) AS QT_NOTAS_FISCAIS,
    NVL(N.QT_ITENS_NOTA,0) AS QT_ITENS_NOTA,
    NVL(RC.QT_EVENTOS_RECEBIMENTO,0) AS QT_EVENTOS_RECEBIMENTO,
    RC.PRIMEIRO_RECEBIMENTO,
    RC.ULTIMO_RECEBIMENTO,
    NVL(RC.VL_RECEBIDO_FINANCEIRO,0) AS VL_RECEBIDO_FINANCEIRO,
    NVL(RC.VL_RECEBIDO_BASE,0) AS VL_RECEBIDO_BASE,
    NVL(RC.VL_ACRESCIMO_RECEBIMENTO,0) AS VL_ACRESCIMO_RECEBIMENTO,
    GREATEST(NVL(RA.VL_TOTAL_CONTA,0) - NVL(RC.VL_RECEBIDO_BASE,0),0) AS VL_SALDO_ESTIMADO,
    CASE
      WHEN RA.CD_REMESSA IS NULL THEN 'SEM_REMESSA'
      WHEN NVL(RC.VL_RECEBIDO_BASE,0) <= 0 AND RF.SN_PAGA = 'S' THEN 'REMESSA_PAGA_SEM_RECEBIMENTO'
      WHEN NVL(RC.VL_RECEBIDO_BASE,0) <= 0 THEN 'AGUARDANDO_RECEBIMENTO'
      WHEN NVL(RC.VL_RECEBIDO_BASE,0) + 0.01 < NVL(RA.VL_TOTAL_CONTA,0) THEN 'PARCIALMENTE_RECEBIDA'
      ELSE 'RECEBIDA'
    END AS STATUS_FINANCEIRO,
    CASE
      WHEN RC.PRIMEIRO_RECEBIMENTO IS NOT NULL AND A.DT_ATENDIMENTO IS NOT NULL
      THEN TRUNC(RC.PRIMEIRO_RECEBIMENTO) - TRUNC(A.DT_ATENDIMENTO)
    END AS DIAS_ATE_PRIMEIRO_RECEBIMENTO
"""

_ATENDIMENTOS_FROM = r"""
FROM CONTAS_ONCO C
JOIN DBAMV.REG_AMB RA ON RA.CD_REG_AMB = C.CD_REG_AMB
JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = C.CD_ATENDIMENTO
LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
LEFT JOIN DBAMV.REMESSA_FATURA RF ON RF.CD_REMESSA = RA.CD_REMESSA
LEFT JOIN GLOSA G ON G.CD_REG_AMB = C.CD_REG_AMB
LEFT JOIN RECEB_CONTA RC ON RC.CD_REG_AMB = C.CD_REG_AMB
LEFT JOIN NOTA_CONTA N ON N.CD_REG_AMB = C.CD_REG_AMB
"""

ATENDIMENTOS_DETALHE = _DETALHES_BASE + _ATENDIMENTOS_SELECT + r""",
    CAST(NULL AS NUMBER) AS VL_CUSTO_MEDICAMENTO
""" + _ATENDIMENTOS_FROM + r"""
ORDER BY A.DT_ATENDIMENTO DESC, C.CD_ATENDIMENTO DESC, C.CD_REG_AMB DESC
"""

ATENDIMENTOS_DETALHE_COM_CUSTO = _DETALHES_BASE + r"""
, CUSTO AS (
    SELECT
        FCA.CD_ATENDIMENTO,
        SUM(NVL(FCA.VL_CUSTO_MEDICAMENTO,0)) AS VL_CUSTO_MEDICAMENTO
    FROM DBAMV.FA_CUSTO_ATENDIMENTO FCA
    JOIN (SELECT DISTINCT CD_ATENDIMENTO FROM CONTAS_ONCO) C
      ON C.CD_ATENDIMENTO = FCA.CD_ATENDIMENTO
    GROUP BY FCA.CD_ATENDIMENTO
)
""" + _ATENDIMENTOS_SELECT + r""",
    NVL(CU.VL_CUSTO_MEDICAMENTO,0) AS VL_CUSTO_MEDICAMENTO
""" + _ATENDIMENTOS_FROM + r"""
LEFT JOIN CUSTO CU ON CU.CD_ATENDIMENTO = C.CD_ATENDIMENTO
ORDER BY A.DT_ATENDIMENTO DESC, C.CD_ATENDIMENTO DESC, C.CD_REG_AMB DESC
"""

_PAC_BASE = _DETALHES_BASE + r"""
, BASE AS (
    SELECT DISTINCT
        P.CD_PACIENTE,
        P.NM_PACIENTE,
        C.CD_ATENDIMENTO,
        C.CD_REG_AMB,
        RA.CD_REMESSA,
        NVL(RA.VL_TOTAL_CONTA,0) AS VL_FATURADO,
        NVL(G.VL_GLOSA_LIQUIDA,0) AS VL_GLOSA_LIQUIDA,
        NVL(RC.VL_RECEBIDO_FINANCEIRO,0) AS VL_RECEBIDO_FINANCEIRO,
        NVL(RC.VL_RECEBIDO_BASE,0) AS VL_RECEBIDO_BASE,
        NVL(RC.VL_ACRESCIMO_RECEBIMENTO,0) AS VL_ACRESCIMO_RECEBIMENTO,
        NVL(RC.QT_EVENTOS_RECEBIMENTO,0) AS QT_EVENTOS_RECEBIMENTO,
        RC.PRIMEIRO_RECEBIMENTO,
        RC.ULTIMO_RECEBIMENTO
    FROM CONTAS_ONCO C
    JOIN DBAMV.REG_AMB RA ON RA.CD_REG_AMB = C.CD_REG_AMB
    JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = C.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
    LEFT JOIN GLOSA G ON G.CD_REG_AMB = C.CD_REG_AMB
    LEFT JOIN RECEB_CONTA RC ON RC.CD_REG_AMB = C.CD_REG_AMB
)
"""

PACIENTES_RESUMO = _PAC_BASE + r"""
SELECT
    CD_PACIENTE,
    NM_PACIENTE,
    COUNT(DISTINCT CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT CD_REG_AMB) AS QT_CONTAS,
    COUNT(DISTINCT CD_REMESSA) AS QT_REMESSAS,
    SUM(VL_FATURADO) AS VL_FATURADO,
    SUM(VL_GLOSA_LIQUIDA) AS VL_GLOSA_LIQUIDA,
    SUM(VL_FATURADO - VL_GLOSA_LIQUIDA) AS VL_POS_GLOSA,
    SUM(VL_RECEBIDO_FINANCEIRO) AS VL_RECEBIDO_FINANCEIRO,
    SUM(VL_RECEBIDO_BASE) AS VL_RECEBIDO_BASE,
    SUM(VL_ACRESCIMO_RECEBIMENTO) AS VL_ACRESCIMO_RECEBIMENTO,
    SUM(GREATEST(VL_FATURADO - VL_RECEBIDO_BASE,0)) AS VL_SALDO_ESTIMADO,
    SUM(QT_EVENTOS_RECEBIMENTO) AS QT_EVENTOS_RECEBIMENTO,
    MIN(PRIMEIRO_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
    MAX(ULTIMO_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
    ROUND(SUM(VL_FATURADO) / NULLIF(COUNT(DISTINCT CD_ATENDIMENTO),0), 2) AS VL_MEDIO_POR_ATENDIMENTO,
    ROUND(SUM(VL_RECEBIDO_BASE) / NULLIF(COUNT(DISTINCT CD_ATENDIMENTO),0), 2) AS VL_RECEBIDO_MEDIO_ATENDIMENTO,
    CAST(NULL AS NUMBER) AS VL_CUSTO_MEDICAMENTO
FROM BASE
GROUP BY CD_PACIENTE, NM_PACIENTE
ORDER BY VL_FATURADO DESC, NM_PACIENTE
"""

PACIENTES_RESUMO_COM_CUSTO = _PAC_BASE + r"""
, CUSTO_PAC AS (
    SELECT
        A.CD_PACIENTE,
        SUM(NVL(FCA.VL_CUSTO_MEDICAMENTO,0)) AS VL_CUSTO_MEDICAMENTO
    FROM DBAMV.FA_CUSTO_ATENDIMENTO FCA
    JOIN (SELECT DISTINCT CD_ATENDIMENTO FROM CONTAS_ONCO) C ON C.CD_ATENDIMENTO = FCA.CD_ATENDIMENTO
    JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = FCA.CD_ATENDIMENTO
    GROUP BY A.CD_PACIENTE
)
SELECT
    B.CD_PACIENTE,
    B.NM_PACIENTE,
    COUNT(DISTINCT B.CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT B.CD_REG_AMB) AS QT_CONTAS,
    COUNT(DISTINCT B.CD_REMESSA) AS QT_REMESSAS,
    SUM(B.VL_FATURADO) AS VL_FATURADO,
    SUM(B.VL_GLOSA_LIQUIDA) AS VL_GLOSA_LIQUIDA,
    SUM(B.VL_FATURADO - B.VL_GLOSA_LIQUIDA) AS VL_POS_GLOSA,
    SUM(B.VL_RECEBIDO_FINANCEIRO) AS VL_RECEBIDO_FINANCEIRO,
    SUM(B.VL_RECEBIDO_BASE) AS VL_RECEBIDO_BASE,
    SUM(B.VL_ACRESCIMO_RECEBIMENTO) AS VL_ACRESCIMO_RECEBIMENTO,
    SUM(GREATEST(B.VL_FATURADO - B.VL_RECEBIDO_BASE,0)) AS VL_SALDO_ESTIMADO,
    SUM(B.QT_EVENTOS_RECEBIMENTO) AS QT_EVENTOS_RECEBIMENTO,
    MIN(B.PRIMEIRO_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
    MAX(B.ULTIMO_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
    ROUND(SUM(B.VL_FATURADO) / NULLIF(COUNT(DISTINCT B.CD_ATENDIMENTO),0), 2) AS VL_MEDIO_POR_ATENDIMENTO,
    ROUND(SUM(B.VL_RECEBIDO_BASE) / NULLIF(COUNT(DISTINCT B.CD_ATENDIMENTO),0), 2) AS VL_RECEBIDO_MEDIO_ATENDIMENTO,
    NVL(MAX(CP.VL_CUSTO_MEDICAMENTO),0) AS VL_CUSTO_MEDICAMENTO
FROM BASE B
LEFT JOIN CUSTO_PAC CP ON CP.CD_PACIENTE = B.CD_PACIENTE
GROUP BY B.CD_PACIENTE, B.NM_PACIENTE
ORDER BY VL_FATURADO DESC, B.NM_PACIENTE
"""

REMESSAS_RESUMO = _DETALHES_BASE + r"""
SELECT
    RA.CD_REMESSA,
    RF.NR_REMESSA_CONVENIO,
    RF.DT_ABERTURA,
    RF.DT_FECHAMENTO,
    RF.DT_ENTREGA_DA_FATURA,
    RF.SN_FECHADA,
    RF.SN_PAGA,
    COUNT(DISTINCT C.CD_REG_AMB) AS QT_CONTAS,
    COUNT(DISTINCT C.CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT P.CD_PACIENTE) AS QT_PACIENTES,
    SUM(NVL(RA.VL_TOTAL_CONTA,0)) AS VL_FATURADO,
    SUM(NVL(G.VL_GLOSA_BRUTA,0)) AS VL_GLOSA_BRUTA,
    SUM(NVL(G.VL_GLOSA_LIQUIDA,0)) AS VL_GLOSA_LIQUIDA,
    SUM(NVL(RA.VL_TOTAL_CONTA,0) - NVL(G.VL_GLOSA_LIQUIDA,0)) AS VL_POS_GLOSA,
    SUM(NVL(RC.VL_RECEBIDO_FINANCEIRO,0)) AS VL_RECEBIDO_FINANCEIRO,
    SUM(NVL(RC.VL_RECEBIDO_BASE,0)) AS VL_RECEBIDO_BASE,
    SUM(NVL(RC.VL_ACRESCIMO_RECEBIMENTO,0)) AS VL_ACRESCIMO_RECEBIMENTO,
    SUM(GREATEST(NVL(RA.VL_TOTAL_CONTA,0) - NVL(RC.VL_RECEBIDO_BASE,0),0)) AS VL_SALDO_ESTIMADO,
    COUNT(DISTINCT CASE WHEN NVL(RC.VL_RECEBIDO_BASE,0) > 0 THEN C.CD_REG_AMB END) AS QT_CONTAS_COM_RECEBIMENTO,
    MIN(RC.PRIMEIRO_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
    MAX(RC.ULTIMO_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
    CASE
      WHEN SUM(NVL(RC.VL_RECEBIDO_BASE,0)) <= 0 AND RF.SN_PAGA='S' THEN 'PAGA_SEM_RECEBIMENTO'
      WHEN SUM(NVL(RC.VL_RECEBIDO_BASE,0)) <= 0 THEN 'AGUARDANDO_RECEBIMENTO'
      WHEN SUM(NVL(RC.VL_RECEBIDO_BASE,0)) + 0.01 < SUM(NVL(RA.VL_TOTAL_CONTA,0)) THEN 'PARCIALMENTE_RECEBIDA'
      ELSE 'RECEBIDA'
    END AS STATUS_RECEBIMENTO
FROM CONTAS_ONCO C
JOIN DBAMV.REG_AMB RA ON RA.CD_REG_AMB = C.CD_REG_AMB
JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = C.CD_ATENDIMENTO
LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
LEFT JOIN DBAMV.REMESSA_FATURA RF ON RF.CD_REMESSA = RA.CD_REMESSA
LEFT JOIN GLOSA G ON G.CD_REG_AMB = C.CD_REG_AMB
LEFT JOIN RECEB_CONTA RC ON RC.CD_REG_AMB = C.CD_REG_AMB
WHERE RA.CD_REMESSA IS NOT NULL
GROUP BY RA.CD_REMESSA, RF.NR_REMESSA_CONVENIO, RF.DT_ABERTURA, RF.DT_FECHAMENTO,
         RF.DT_ENTREGA_DA_FATURA, RF.SN_FECHADA, RF.SN_PAGA
ORDER BY RF.DT_FECHAMENTO DESC NULLS LAST, RA.CD_REMESSA DESC
"""

# V6.3 - navegação operacional por paciente/conta.
# Mantém o coorte de produção para a lista por paciente e usa a conta exata no drill-down.
PACIENTE_CONTAS = _DETALHES_BASE + _ATENDIMENTOS_SELECT + r""",
    CAST(NULL AS NUMBER) AS VL_CUSTO_MEDICAMENTO
""" + _ATENDIMENTOS_FROM + r"""
WHERE P.CD_PACIENTE = :cd_paciente
ORDER BY A.DT_ATENDIMENTO DESC, C.CD_ATENDIMENTO DESC, C.CD_REG_AMB DESC
"""

CONTA_CABECALHO = r"""
WITH GLOSA AS (
    SELECT
        G.CD_REG_AMB,
        COUNT(DISTINCT G.CD_GLOSAS) AS QT_EVENTOS_GLOSA,
        SUM(NVL(G.VL_GLOSA,0)) AS VL_GLOSA_BRUTA,
        SUM(CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN 0 ELSE NVL(G.VL_GLOSA,0) END) AS VL_GLOSA_LIQUIDA,
        SUM(NVL(G.VL_REAPRESENTADO,0)) AS VL_REAPRESENTADO,
        SUM(NVL(G.VL_RECURSO_REPASSADO,0)) AS VL_RECURSO_REPASSADO
    FROM DBAMV.GLOSAS G
    WHERE G.CD_REG_AMB = :cd_reg_amb
    GROUP BY G.CD_REG_AMB
),
CONTA_ATEND AS (
    SELECT
        IRA.CD_REG_AMB,
        MIN(IRA.CD_ATENDIMENTO) AS CD_ATENDIMENTO,
        COUNT(DISTINCT IRA.CD_ATENDIMENTO) AS QT_ATENDIMENTOS_CONTA
    FROM DBAMV.ITREG_AMB IRA
    WHERE IRA.CD_REG_AMB = :cd_reg_amb
      AND IRA.CD_CONVENIO = 11
    GROUP BY IRA.CD_REG_AMB
),
RECEB AS (
    SELECT
        INF.CD_REG_AMB,
        COUNT(DISTINCT R.CD_RECCON_REC) AS QT_EVENTOS_RECEBIMENTO,
        MIN(R.DT_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
        MAX(R.DT_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(V.VL_RECEBIDO,0)-NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(V.VL_ACRESCIMO,0)) AS VL_ACRESCIMO_RECEBIMENTO,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA_RECEBIMENTO
    FROM DBAMV.ITFAT_NOTA_FISCAL INF
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE INF.CD_REG_AMB = :cd_reg_amb
      AND R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB
)
SELECT
    P.CD_PACIENTE,
    P.NM_PACIENTE,
    A.CD_ATENDIMENTO,
    A.DT_ATENDIMENTO,
    RA.CD_REG_AMB,
    RA.DT_LANCAMENTO,
    RA.CD_REMESSA,
    RA.DT_REMESSA,
    RF.NR_REMESSA_CONVENIO,
    RF.DT_ABERTURA AS DT_ABERTURA_REMESSA,
    RF.DT_FECHAMENTO AS DT_FECHAMENTO_REMESSA,
    RF.DT_ENTREGA_DA_FATURA,
    RF.SN_FECHADA,
    RF.SN_PAGA,
    RA.CD_CONVENIO,
    NVL(RA.VL_TOTAL_CONTA,0) AS VL_FATURADO,
    NVL(G.VL_GLOSA_BRUTA,0) AS VL_GLOSA_BRUTA,
    NVL(G.VL_GLOSA_LIQUIDA,0) AS VL_GLOSA_LIQUIDA,
    NVL(G.VL_REAPRESENTADO,0) AS VL_REAPRESENTADO,
    NVL(G.VL_RECURSO_REPASSADO,0) AS VL_RECURSO_REPASSADO,
    NVL(R.VL_RECEBIDO_FINANCEIRO,0) AS VL_RECEBIDO_FINANCEIRO,
    NVL(R.VL_RECEBIDO_BASE,0) AS VL_RECEBIDO_BASE,
    NVL(R.VL_ACRESCIMO_RECEBIMENTO,0) AS VL_ACRESCIMO_RECEBIMENTO,
    NVL(R.VL_GLOSA_RECEBIMENTO,0) AS VL_GLOSA_RECEBIMENTO,
    NVL(R.QT_EVENTOS_RECEBIMENTO,0) AS QT_EVENTOS_RECEBIMENTO,
    R.PRIMEIRO_RECEBIMENTO,
    R.ULTIMO_RECEBIMENTO,
    GREATEST(NVL(RA.VL_TOTAL_CONTA,0)-NVL(R.VL_RECEBIDO_BASE,0),0) AS VL_SALDO_ESTIMADO,
    CASE
      WHEN RA.CD_REMESSA IS NULL THEN 'SEM_REMESSA'
      WHEN NVL(R.VL_RECEBIDO_BASE,0) <= 0 AND RF.SN_PAGA='S' THEN 'REMESSA_PAGA_SEM_RECEBIMENTO'
      WHEN NVL(R.VL_RECEBIDO_BASE,0) <= 0 THEN 'AGUARDANDO_RECEBIMENTO'
      WHEN NVL(R.VL_RECEBIDO_BASE,0) + 0.01 < NVL(RA.VL_TOTAL_CONTA,0) THEN 'PARCIALMENTE_RECEBIDA'
      WHEN NVL(G.VL_GLOSA_LIQUIDA,0) > 0 THEN 'RECEBIDA_COM_GLOSA'
      ELSE 'RECEBIDA'
    END AS STATUS_FINANCEIRO
FROM DBAMV.REG_AMB RA
JOIN CONTA_ATEND CA ON CA.CD_REG_AMB = RA.CD_REG_AMB
JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = CA.CD_ATENDIMENTO
LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
LEFT JOIN DBAMV.REMESSA_FATURA RF ON RF.CD_REMESSA = RA.CD_REMESSA
LEFT JOIN GLOSA G ON G.CD_REG_AMB = RA.CD_REG_AMB
LEFT JOIN RECEB R ON R.CD_REG_AMB = RA.CD_REG_AMB
WHERE RA.CD_REG_AMB = :cd_reg_amb
  AND RA.CD_CONVENIO = 11
  AND EXISTS (
      SELECT 1 FROM DBAMV.ITREG_AMB IRA
      JOIN DBAMV.AGENDAMENTO_ONCOLOGICO AO ON AO.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
      WHERE IRA.CD_REG_AMB = RA.CD_REG_AMB
        AND IRA.CD_CONVENIO = 11
        AND AO.CD_CONVENIO = 11
  )
"""

CONTA_ITENS = r"""
SELECT
    IRA.CD_REG_AMB,
    IRA.CD_LANCAMENTO,
    IRA.DT_PRODUCAO,
    IRA.DT_SESSAO,
    IRA.CD_PRO_FAT,
    PF.DS_PRO_FAT,
    IRA.QT_LANCAMENTO,
    IRA.VL_UNITARIO,
    IRA.VL_TOTAL_CONTA,
    IRA.CD_GUIA,
    IRA.CD_ITMVTO
FROM DBAMV.ITREG_AMB IRA
LEFT JOIN DBAMV.PRO_FAT PF ON PF.CD_PRO_FAT = IRA.CD_PRO_FAT
WHERE IRA.CD_REG_AMB = :cd_reg_amb
  AND IRA.CD_CONVENIO = 11
ORDER BY NVL(IRA.DT_SESSAO, IRA.DT_PRODUCAO), IRA.CD_LANCAMENTO
"""

CONTA_GLOSAS = r"""
SELECT
    G.CD_GLOSAS,
    G.DT_GLOSA,
    G.CD_MOTIVO_GLOSA,
    MG.DS_MOTIVO_GLOSA,
    G.CD_PRO_FAT,
    PF.DS_PRO_FAT,
    NVL(G.VL_GLOSA,0) AS VL_GLOSA,
    NVL(G.VL_REAPRESENTADO,0) AS VL_REAPRESENTADO,
    NVL(G.VL_RECEBIDO,0) AS VL_RECEBIDO,
    NVL(G.VL_RECURSO_REPASSADO,0) AS VL_RECURSO_REPASSADO,
    G.SN_EM_ANALISE
FROM DBAMV.GLOSAS G
LEFT JOIN DBAMV.MOTIVO_GLOSA MG ON MG.CD_MOTIVO_GLOSA = G.CD_MOTIVO_GLOSA
LEFT JOIN DBAMV.PRO_FAT PF ON PF.CD_PRO_FAT = G.CD_PRO_FAT
WHERE G.CD_REG_AMB = :cd_reg_amb
ORDER BY G.DT_GLOSA DESC, G.CD_GLOSAS DESC
"""

CONTA_RECEBIMENTOS = r"""
SELECT
    R.CD_RECCON_REC,
    R.DT_RECEBIMENTO,
    SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
    SUM(NVL(V.VL_RECEBIDO,0)-NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
    SUM(NVL(V.VL_ACRESCIMO,0)) AS VL_ACRESCIMO,
    SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA,
    SUM(NVL(V.VL_DESCONTO,0)) AS VL_DESCONTO,
    SUM(NVL(V.VL_IMPOSTO_RETIDO,0)) AS VL_IMPOSTO_RETIDO
FROM DBAMV.ITFAT_NOTA_FISCAL INF
JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
JOIN DBAMV.RECCON_REC R ON R.CD_RECCON_REC = V.CD_RECCON_REC
WHERE INF.CD_REG_AMB = :cd_reg_amb
  AND R.DT_ESTORNO IS NULL
GROUP BY R.CD_RECCON_REC, R.DT_RECEBIMENTO
ORDER BY R.DT_RECEBIMENTO DESC, R.CD_RECCON_REC DESC
"""

