"""Faturamento por competência usando a regra estrutural do relatório nativo MV.

O SQL reproduz os filtros visíveis no relatório fornecido pelo usuário. Não aplica
recorte adicional por AGENDAMENTO_ONCOLOGICO, porque esse filtro não existe na SQL
nativa enviada. O recorte assistencial deve ser reproduzido pelos mesmos códigos
de setor do relatório MV. O placeholder dinâmico {V_VAR} não é interpolado por
segurança; filtros de setor são suportados apenas como IDs inteiros bindados.
"""

_BASE = r"""
WITH FATURAMENTO_NATIVE AS (
    SELECT
        'HOSPITALAR' AS ORIGEM,
        RF.CD_REG_FAT AS CD_CONTA,
        RF.CD_ATENDIMENTO,
        RF.CD_REMESSA,
        NVL(IRF.CD_SETOR_PRODUZIU, IRF.CD_SETOR) AS CD_SETOR,
        S.NM_SETOR,
        TRUNC(F.DT_COMPETENCIA, 'MM') AS DT_COMPETENCIA,
        NVL(ILM.VL_LIQUIDO, IRF.VL_TOTAL_CONTA) AS VL_TOTAL
    FROM DBAMV.REG_FAT RF
    JOIN DBAMV.ITREG_FAT IRF
      ON IRF.CD_REG_FAT = RF.CD_REG_FAT
    JOIN DBAMV.PRO_FAT PF
      ON PF.CD_PRO_FAT = IRF.CD_PRO_FAT
    JOIN DBAMV.GRU_PRO GP
      ON GP.CD_GRU_PRO = PF.CD_GRU_PRO
    JOIN DBAMV.REMESSA_FATURA REM
      ON REM.CD_REMESSA = RF.CD_REMESSA
    JOIN DBAMV.FATURA F
      ON F.CD_FATURA = REM.CD_FATURA
    JOIN DBAMV.CONVENIO C
      ON C.CD_CONVENIO = RF.CD_CONVENIO
    JOIN DBAMV.ATENDIME A
      ON A.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
    JOIN DBAMV.ORI_ATE OA
      ON OA.CD_ORI_ATE = A.CD_ORI_ATE
    JOIN DBAMV.EMPRESA_CONVENIO EC
      ON EC.CD_CONVENIO = C.CD_CONVENIO
     AND EC.CD_MULTI_EMPRESA = 1
    LEFT JOIN DBAMV.ITLAN_MED ILM
      ON ILM.CD_REG_FAT = IRF.CD_REG_FAT
     AND ILM.CD_LANCAMENTO = IRF.CD_LANCAMENTO
    LEFT JOIN DBAMV.SETOR S
      ON S.CD_SETOR = NVL(IRF.CD_SETOR_PRODUZIU, IRF.CD_SETOR)
    WHERE RF.CD_MULTI_EMPRESA = 1
      AND RF.CD_CONVENIO = 11
      AND C.TP_CONVENIO <> 'H'
      AND NVL(IRF.SN_PERTENCE_PACOTE, 'N') = 'N'
      AND NVL(RF.SN_DIAGNO, 'N') = 'N'
      AND NVL(NVL(ILM.TP_PAGAMENTO, IRF.TP_PAGAMENTO), 'P') <> 'C'
      AND RF.SN_FECHADA = 'S'
      AND REM.SN_FECHADA = 'S'
      AND F.DT_COMPETENCIA >= :data_inicio
      AND F.DT_COMPETENCIA < :data_fim + 1
      /*SETOR_FILTER_HOSP*/

    UNION ALL

    SELECT
        'AMBULATORIAL' AS ORIGEM,
        RA.CD_REG_AMB AS CD_CONTA,
        IRA.CD_ATENDIMENTO,
        RA.CD_REMESSA,
        NVL(IRA.CD_SETOR_PRODUZIU, IRA.CD_SETOR) AS CD_SETOR,
        S.NM_SETOR,
        TRUNC(F.DT_COMPETENCIA, 'MM') AS DT_COMPETENCIA,
        IRA.VL_TOTAL_CONTA AS VL_TOTAL
    FROM DBAMV.REG_AMB RA
    JOIN DBAMV.ITREG_AMB IRA
      ON IRA.CD_REG_AMB = RA.CD_REG_AMB
    JOIN DBAMV.PRO_FAT PF
      ON PF.CD_PRO_FAT = IRA.CD_PRO_FAT
    JOIN DBAMV.GRU_PRO GP
      ON GP.CD_GRU_PRO = PF.CD_GRU_PRO
    JOIN DBAMV.REMESSA_FATURA REM
      ON REM.CD_REMESSA = RA.CD_REMESSA
    JOIN DBAMV.FATURA F
      ON F.CD_FATURA = REM.CD_FATURA
    JOIN DBAMV.CONVENIO C
      ON C.CD_CONVENIO = IRA.CD_CONVENIO
    JOIN DBAMV.ATENDIME A
      ON A.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
    JOIN DBAMV.ORI_ATE OA
      ON OA.CD_ORI_ATE = A.CD_ORI_ATE
    JOIN DBAMV.EMPRESA_CONVENIO EC
      ON EC.CD_CONVENIO = C.CD_CONVENIO
     AND EC.CD_MULTI_EMPRESA = 1
    LEFT JOIN DBAMV.SETOR S
      ON S.CD_SETOR = NVL(IRA.CD_SETOR_PRODUZIU, IRA.CD_SETOR)
    WHERE RA.CD_MULTI_EMPRESA = 1
      AND RA.CD_CONVENIO = 11
      AND IRA.CD_CONVENIO = 11
      AND C.TP_CONVENIO <> 'A'
      AND NVL(IRA.SN_PERTENCE_PACOTE, 'N') = 'N'
      AND NVL(RA.SN_DIAGNO, 'N') = 'N'
      AND NVL(IRA.TP_PAGAMENTO, 'X') <> 'C'
      AND REM.SN_FECHADA = 'S'
      AND IRA.SN_FECHADA = 'S'
      AND F.DT_COMPETENCIA >= :data_inicio
      AND F.DT_COMPETENCIA < :data_fim + 1
      /*SETOR_FILTER_AMB*/
)
"""

FATURAMENTO_COMPETENCIA_RESUMO = _BASE + r"""
SELECT
    COUNT(*) AS QT_ITENS,
    COUNT(DISTINCT ORIGEM || ':' || TO_CHAR(CD_CONTA)) AS QT_CONTAS,
    COUNT(DISTINCT CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT CD_REMESSA) AS QT_REMESSAS,
    COUNT(DISTINCT CD_SETOR) AS QT_SETORES,
    SUM(NVL(VL_TOTAL, 0)) AS VL_FATURAMENTO_COMPETENCIA,
    SUM(CASE WHEN ORIGEM = 'AMBULATORIAL' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_AMBULATORIAL,
    SUM(CASE WHEN ORIGEM = 'HOSPITALAR' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_HOSPITALAR,
    COUNT(CASE WHEN ORIGEM = 'AMBULATORIAL' THEN 1 END) AS QT_ITENS_AMBULATORIAL,
    COUNT(CASE WHEN ORIGEM = 'HOSPITALAR' THEN 1 END) AS QT_ITENS_HOSPITALAR
FROM FATURAMENTO_NATIVE
"""

FATURAMENTO_COMPETENCIA_MENSAL = _BASE + r"""
SELECT
    TO_CHAR(DT_COMPETENCIA, 'YYYY-MM') AS COMPETENCIA,
    SUM(NVL(VL_TOTAL, 0)) AS VL_FATURAMENTO_COMPETENCIA,
    SUM(CASE WHEN ORIGEM = 'AMBULATORIAL' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_AMBULATORIAL,
    SUM(CASE WHEN ORIGEM = 'HOSPITALAR' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_HOSPITALAR,
    COUNT(*) AS QT_ITENS,
    COUNT(DISTINCT ORIGEM || ':' || TO_CHAR(CD_CONTA)) AS QT_CONTAS,
    COUNT(DISTINCT CD_REMESSA) AS QT_REMESSAS
FROM FATURAMENTO_NATIVE
GROUP BY DT_COMPETENCIA
ORDER BY DT_COMPETENCIA
"""

FATURAMENTO_COMPETENCIA_SETORES = _BASE + r"""
SELECT
    CD_SETOR,
    NVL(NM_SETOR, 'SETOR NAO IDENTIFICADO') AS NM_SETOR,
    SUM(NVL(VL_TOTAL, 0)) AS VL_FATURAMENTO_COMPETENCIA,
    SUM(CASE WHEN ORIGEM = 'AMBULATORIAL' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_AMBULATORIAL,
    SUM(CASE WHEN ORIGEM = 'HOSPITALAR' THEN NVL(VL_TOTAL, 0) ELSE 0 END) AS VL_HOSPITALAR,
    COUNT(*) AS QT_ITENS,
    COUNT(DISTINCT ORIGEM || ':' || TO_CHAR(CD_CONTA)) AS QT_CONTAS,
    COUNT(DISTINCT CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT CD_REMESSA) AS QT_REMESSAS
FROM FATURAMENTO_NATIVE
GROUP BY CD_SETOR, NM_SETOR
ORDER BY VL_FATURAMENTO_COMPETENCIA DESC, NM_SETOR
"""
