from .common import ONCO_BASE

FINANCEIRO_RESUMO = ONCO_BASE + """
, BASE AS (
    SELECT DISTINCT
           C.CD_REG_AMB,
           C.CD_ATENDIMENTO,
           RA.CD_REMESSA,
           RA.VL_TOTAL_CONTA,
           RA.DT_LANCAMENTO,
           RA.DT_REMESSA,
           RF.SN_PAGA,
           RF.DT_PREVISTA_PARA_PGTO
    FROM CONTAS_ONCO C
    JOIN DBAMV.REG_AMB RA
      ON RA.CD_REG_AMB = C.CD_REG_AMB
    LEFT JOIN DBAMV.REMESSA_FATURA RF
      ON RF.CD_REMESSA = RA.CD_REMESSA
),
GLOSA_BASE AS (
    SELECT
        G.CD_GLOSAS,
        G.CD_REG_AMB,
        G.CD_ATENDIMENTO,
        G.CD_MOTIVO_GLOSA,
        NVL(G.VL_GLOSA,0) AS VL_GLOSA
    FROM DBAMV.GLOSAS G
    JOIN CONTAS_ONCO C
      ON C.CD_REG_AMB = G.CD_REG_AMB
)
SELECT
    (SELECT COUNT(*) FROM BASE) AS QT_CONTAS,
    (SELECT COUNT(DISTINCT CD_ATENDIMENTO) FROM BASE) AS QT_ATENDIMENTOS,
    (SELECT COUNT(DISTINCT CD_REMESSA) FROM BASE WHERE CD_REMESSA IS NOT NULL) AS QT_REMESSAS,
    (SELECT COUNT(DISTINCT CD_REMESSA) FROM BASE WHERE SN_PAGA = 'S') AS QT_REMESSAS_PAGAS,
    (SELECT COUNT(DISTINCT CD_REMESSA) FROM BASE WHERE CD_REMESSA IS NOT NULL AND NVL(SN_PAGA,'N') <> 'S') AS QT_REMESSAS_NAO_PAGAS,
    (SELECT SUM(NVL(VL_TOTAL_CONTA,0)) FROM BASE) AS VL_FATURADO,
    (SELECT SUM(CASE WHEN CD_REMESSA IS NOT NULL THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) FROM BASE) AS VL_REMETIDO,
    (SELECT SUM(CASE WHEN CD_REMESSA IS NULL THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) FROM BASE) AS VL_NAO_REMETIDO,
    (SELECT SUM(CASE WHEN SN_PAGA = 'S' THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) FROM BASE) AS VL_REMESSAS_PAGAS,
    (SELECT SUM(CASE WHEN CD_REMESSA IS NOT NULL AND NVL(SN_PAGA,'N') <> 'S'
                     THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) FROM BASE) AS VL_REMESSAS_NAO_PAGAS,
    (SELECT COUNT(DISTINCT CD_REG_AMB) FROM GLOSA_BASE) AS QT_CONTAS_COM_GLOSA,
    (SELECT COUNT(DISTINCT CD_GLOSAS) FROM GLOSA_BASE) AS QT_EVENTOS_GLOSA,
    (SELECT SUM(VL_GLOSA) FROM GLOSA_BASE) AS VL_GLOSA_BRUTA,
    (SELECT SUM(CASE WHEN CD_MOTIVO_GLOSA = 324 THEN VL_GLOSA ELSE 0 END) FROM GLOSA_BASE) AS VL_GLOSA_REVERTIDA,
    (SELECT SUM(CASE WHEN CD_MOTIVO_GLOSA = 324 THEN 0 ELSE VL_GLOSA END) FROM GLOSA_BASE) AS VL_GLOSA_LIQUIDA
FROM DUAL
"""

FINANCEIRO_MENSAL = ONCO_BASE + """
, BASE AS (
    SELECT DISTINCT
           C.CD_REG_AMB,
           RA.CD_REMESSA,
           RA.VL_TOTAL_CONTA,
           RA.DT_LANCAMENTO,
           RF.SN_PAGA
    FROM CONTAS_ONCO C
    JOIN DBAMV.REG_AMB RA
      ON RA.CD_REG_AMB = C.CD_REG_AMB
    LEFT JOIN DBAMV.REMESSA_FATURA RF
      ON RF.CD_REMESSA = RA.CD_REMESSA
)
SELECT
    TO_CHAR(TRUNC(DT_LANCAMENTO,'MM'),'YYYY-MM') AS MES,
    SUM(NVL(VL_TOTAL_CONTA,0)) AS VL_FATURADO,
    SUM(CASE WHEN CD_REMESSA IS NOT NULL THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) AS VL_REMETIDO,
    SUM(CASE WHEN CD_REMESSA IS NULL THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) AS VL_NAO_REMETIDO,
    SUM(CASE WHEN SN_PAGA = 'S' THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) AS VL_REMESSAS_PAGAS,
    SUM(CASE WHEN CD_REMESSA IS NOT NULL AND NVL(SN_PAGA,'N') <> 'S'
             THEN NVL(VL_TOTAL_CONTA,0) ELSE 0 END) AS VL_REMESSAS_NAO_PAGAS
FROM BASE
GROUP BY TRUNC(DT_LANCAMENTO,'MM')
ORDER BY TRUNC(DT_LANCAMENTO,'MM')
"""
