from .common import ONCO_BASE

GLOSAS_MOTIVOS = ONCO_BASE + """
SELECT
    G.CD_MOTIVO_GLOSA,
    MG.DS_MOTIVO_GLOSA,
    COUNT(DISTINCT G.CD_GLOSAS) AS QT_GLOSAS,
    COUNT(DISTINCT G.CD_REG_AMB) AS QT_CONTAS,
    SUM(NVL(G.VL_GLOSA,0)) AS VL_GLOSA,
    SUM(CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN NVL(G.VL_GLOSA,0) ELSE 0 END) AS VL_REVERTIDA,
    SUM(CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN 0 ELSE NVL(G.VL_GLOSA,0) END) AS VL_LIQUIDA
FROM DBAMV.GLOSAS G
JOIN CONTAS_ONCO C
  ON C.CD_REG_AMB = G.CD_REG_AMB
LEFT JOIN DBAMV.MOTIVO_GLOSA MG
  ON MG.CD_MOTIVO_GLOSA = G.CD_MOTIVO_GLOSA
GROUP BY G.CD_MOTIVO_GLOSA, MG.DS_MOTIVO_GLOSA
ORDER BY VL_GLOSA DESC
"""

GLOSAS_DETALHE = ONCO_BASE + """
SELECT
    G.CD_GLOSAS,
    G.CD_REG_AMB,
    G.CD_ATENDIMENTO,
    G.CD_PRO_FAT,
    PF.DS_PRO_FAT,
    G.DT_GLOSA,
    G.VL_GLOSA,
    G.CD_MOTIVO_GLOSA,
    MG.DS_MOTIVO_GLOSA,
    CASE WHEN G.CD_MOTIVO_GLOSA = 324 THEN 'REVERTIDA'
         ELSE 'ATIVA' END AS STATUS_ANALITICO
FROM DBAMV.GLOSAS G
JOIN CONTAS_ONCO C
  ON C.CD_REG_AMB = G.CD_REG_AMB
LEFT JOIN DBAMV.MOTIVO_GLOSA MG
  ON MG.CD_MOTIVO_GLOSA = G.CD_MOTIVO_GLOSA
LEFT JOIN DBAMV.PRO_FAT PF
  ON PF.CD_PRO_FAT = G.CD_PRO_FAT
ORDER BY G.DT_GLOSA DESC, G.CD_GLOSAS DESC
"""
