"""Consultas de conciliacao financeira real do fluxo oncologico CONVENIO_DEMO.

Modelo validado em homologacao:
  V_FNCP_ITEM_CONVENIO -> V_AJUSTES_RECEBIMENTO_DET -> RECCON_REC
com ITFAT_NOTA_FISCAL como ponte para conta/remessa.

O periodo destes endpoints e aplicado a RECCON_REC.DT_RECEBIMENTO.
"""

PAGAMENTOS_BASE = r"""
WITH REC_PERIODO AS (
    SELECT
        R.CD_RECCON_REC,
        R.DT_RECEBIMENTO,
        R.DT_BAIXA,
        R.DT_ESTORNO,
        R.VL_RECEBIDO AS VL_EVENTO_TOTAL,
        R.VL_ESTORNO,
        R.TP_RECEBIMENTO,
        R.CD_SISTEMA_BAIXA
    FROM DBAMV.RECCON_REC R
    WHERE R.DT_RECEBIMENTO >= :data_inicio
      AND R.DT_RECEBIMENTO < :data_fim + 1
),
BASE AS (
    SELECT
        R.CD_RECCON_REC,
        R.DT_RECEBIMENTO,
        R.DT_BAIXA,
        R.DT_ESTORNO,
        R.VL_EVENTO_TOTAL,
        R.VL_ESTORNO,
        R.TP_RECEBIMENTO,
        R.CD_SISTEMA_BAIXA,
        V.CD_ITFAT_NF,
        V.CD_RECCON_REC AS CD_RECCON_REC_V,
        NVL(V.VL_RECEBIDO,0) AS VL_RECEBIDO_FINANCEIRO,
        NVL(V.VL_GLOSA,0) AS VL_GLOSA_RECEBIMENTO,
        NVL(V.VL_DESCONTO,0) AS VL_DESCONTO,
        NVL(V.VL_ACRESCIMO,0) AS VL_ACRESCIMO,
        NVL(V.VL_IMPOSTO_RETIDO,0) AS VL_IMPOSTO_RETIDO,
        NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0) AS VL_RECEBIDO_BASE,
        INF.CD_REG_AMB,
        INF.CD_REMESSA,
        INF.CD_NOTA_FISCAL,
        INF.CD_ATENDIMENTO,
        F.CD_CONVENIO,
        F.DT_COMPETENCIA,
        F.DT_ATENDIMENTO,
        NVL(F.VL_FATURADO,0) AS VL_FATURADO_ITEM,
        A.CD_PACIENTE,
        COALESCE(P.NM_PACIENTE, F.NM_PACIENTE) AS NM_PACIENTE
    FROM REC_PERIODO R
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V
      ON V.CD_RECCON_REC = R.CD_RECCON_REC
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF
      ON INF.CD_ITFAT_NF = V.CD_ITFAT_NF
    JOIN DBAMV.V_FNCP_ITEM_CONVENIO F
      ON F.CD_ITFAT_NF = V.CD_ITFAT_NF
     AND F.CD_CONVENIO = 11
    LEFT JOIN DBAMV.ATENDIME A
      ON A.CD_ATENDIMENTO = F.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE P
      ON P.CD_PACIENTE = A.CD_PACIENTE
    WHERE EXISTS (
        SELECT 1
        FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
        WHERE AO.CD_ATENDIMENTO = F.CD_ATENDIMENTO
          AND AO.CD_CONVENIO = 11
    )
)
"""

PAGAMENTOS_RESUMO = PAGAMENTOS_BASE + r"""
, ITENS AS (
    SELECT
        CD_ITFAT_NF,
        COUNT(DISTINCT CASE WHEN DT_ESTORNO IS NULL THEN CD_RECCON_REC END) AS QT_RECEBIMENTOS
    FROM BASE
    GROUP BY CD_ITFAT_NF
), ITEM_STATS AS (
    SELECT
        SUM(CASE WHEN QT_RECEBIMENTOS > 1 THEN 1 ELSE 0 END) AS QT_ITENS_MULTIPLOS_RECEBIMENTOS,
        MAX(QT_RECEBIMENTOS) AS MAX_RECEBIMENTOS_POR_ITEM
    FROM ITENS
)
SELECT
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_RECCON_REC END) AS QT_EVENTOS_RECEBIMENTO,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_REMESSA END) AS QT_REMESSAS_RECEBIDAS,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_REG_AMB END) AS QT_CONTAS_RECEBIDAS,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_PACIENTE END) AS QT_PACIENTES,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_ATENDIMENTO END) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NULL THEN B.CD_ITFAT_NF END) AS QT_ITENS_RECEBIDOS,
    MAX(I.QT_ITENS_MULTIPLOS_RECEBIMENTOS) AS QT_ITENS_MULTIPLOS_RECEBIMENTOS,
    MAX(I.MAX_RECEBIMENTOS_POR_ITEM) AS MAX_RECEBIMENTOS_POR_ITEM,
    MIN(CASE WHEN B.DT_ESTORNO IS NULL THEN B.DT_RECEBIMENTO END) AS PRIMEIRO_RECEBIMENTO,
    MAX(CASE WHEN B.DT_ESTORNO IS NULL THEN B.DT_RECEBIMENTO END) AS ULTIMO_RECEBIMENTO,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_RECEBIDO_FINANCEIRO ELSE 0 END) AS VL_RECEBIDO_FINANCEIRO,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_RECEBIDO_BASE ELSE 0 END) AS VL_RECEBIDO_BASE,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_ACRESCIMO ELSE 0 END) AS VL_ACRESCIMO,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_DESCONTO ELSE 0 END) AS VL_DESCONTO,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_IMPOSTO_RETIDO ELSE 0 END) AS VL_IMPOSTO_RETIDO,
    SUM(CASE WHEN B.DT_ESTORNO IS NULL THEN B.VL_GLOSA_RECEBIMENTO ELSE 0 END) AS VL_GLOSA_RECEBIMENTO,
    COUNT(DISTINCT CASE WHEN B.DT_ESTORNO IS NOT NULL THEN B.CD_RECCON_REC END) AS QT_EVENTOS_ESTORNADOS,
    SUM(CASE WHEN B.DT_ESTORNO IS NOT NULL THEN B.VL_RECEBIDO_FINANCEIRO ELSE 0 END) AS VL_RECEBIMENTO_ESTORNADO
FROM BASE B
CROSS JOIN ITEM_STATS I
"""

PAGAMENTOS_COMPETENCIA = PAGAMENTOS_BASE + r"""
SELECT
    TO_CHAR(TRUNC(DT_COMPETENCIA,'MM'),'YYYY-MM') AS COMPETENCIA,
    TO_CHAR(TRUNC(DT_RECEBIMENTO,'MM'),'YYYY-MM') AS MES_RECEBIMENTO,
    COUNT(DISTINCT CD_ATENDIMENTO) AS QT_ATENDIMENTOS,
    COUNT(DISTINCT CD_REG_AMB) AS QT_CONTAS,
    COUNT(DISTINCT CD_ITFAT_NF) AS QT_ITENS,
    SUM(VL_RECEBIDO_FINANCEIRO) AS VL_RECEBIDO_FINANCEIRO,
    SUM(VL_RECEBIDO_BASE) AS VL_RECEBIDO_BASE,
    SUM(VL_ACRESCIMO) AS VL_ACRESCIMO,
    SUM(VL_GLOSA_RECEBIMENTO) AS VL_GLOSA
FROM BASE
WHERE DT_ESTORNO IS NULL
GROUP BY TRUNC(DT_COMPETENCIA,'MM'), TRUNC(DT_RECEBIMENTO,'MM')
ORDER BY TRUNC(DT_RECEBIMENTO,'MM'), TRUNC(DT_COMPETENCIA,'MM')
"""

PAGAMENTOS_EVENTOS = PAGAMENTOS_BASE + r"""
SELECT
    CD_RECCON_REC,
    DT_RECEBIMENTO,
    MAX(DT_BAIXA) AS DT_BAIXA,
    MAX(DT_ESTORNO) AS DT_ESTORNO,
    MAX(TP_RECEBIMENTO) AS TP_RECEBIMENTO,
    MAX(CD_SISTEMA_BAIXA) AS CD_SISTEMA_BAIXA,
    MAX(VL_EVENTO_TOTAL) AS VL_EVENTO_TOTAL,
    COUNT(DISTINCT CD_REMESSA) AS QT_REMESSAS_ONCO,
    COUNT(DISTINCT CD_REG_AMB) AS QT_CONTAS_ONCO,
    COUNT(DISTINCT CD_PACIENTE) AS QT_PACIENTES_ONCO,
    COUNT(DISTINCT CD_ATENDIMENTO) AS QT_ATENDIMENTOS_ONCO,
    COUNT(DISTINCT CD_ITFAT_NF) AS QT_ITENS_ONCO,
    SUM(VL_RECEBIDO_FINANCEIRO) AS VL_ONCO_RECEBIDO,
    SUM(VL_RECEBIDO_BASE) AS VL_ONCO_BASE,
    SUM(VL_ACRESCIMO) AS VL_ONCO_ACRESCIMO,
    SUM(VL_GLOSA_RECEBIMENTO) AS VL_ONCO_GLOSA,
    ROUND(
        CASE WHEN MAX(VL_EVENTO_TOTAL) <> 0
             THEN SUM(VL_RECEBIDO_FINANCEIRO) / MAX(VL_EVENTO_TOTAL) * 100
        END,
        2
    ) AS PCT_ONCO_EVENTO
FROM BASE
GROUP BY CD_RECCON_REC, DT_RECEBIMENTO
ORDER BY DT_RECEBIMENTO DESC, CD_RECCON_REC DESC
"""

PAGAMENTOS_CONTAS = PAGAMENTOS_BASE + r"""
, CONTAS_PERIODO AS (
    SELECT DISTINCT CD_REG_AMB
    FROM BASE
    WHERE DT_ESTORNO IS NULL
),
FAT_CONTA AS (
    SELECT
        INF.CD_REG_AMB,
        MAX(INF.CD_REMESSA) AS CD_REMESSA,
        MAX(F.CD_ATENDIMENTO) AS CD_ATENDIMENTO,
        MAX(A.CD_PACIENTE) AS CD_PACIENTE,
        MAX(COALESCE(P.NM_PACIENTE,F.NM_PACIENTE)) AS NM_PACIENTE,
        MIN(F.DT_ATENDIMENTO) AS DT_ATENDIMENTO,
        MIN(F.DT_COMPETENCIA) AS DT_COMPETENCIA,
        SUM(NVL(F.VL_FATURADO,0)) AS VL_FATURADO
    FROM CONTAS_PERIODO CP
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF
      ON INF.CD_REG_AMB = CP.CD_REG_AMB
    JOIN DBAMV.V_FNCP_ITEM_CONVENIO F
      ON F.CD_ITFAT_NF = INF.CD_ITFAT_NF
     AND F.CD_CONVENIO = 11
    LEFT JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = F.CD_ATENDIMENTO
    LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
    WHERE EXISTS (
        SELECT 1 FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
        WHERE AO.CD_ATENDIMENTO = F.CD_ATENDIMENTO
          AND AO.CD_CONVENIO = 11
    )
    GROUP BY INF.CD_REG_AMB
),
REC_PERIODO_CONTA AS (
    SELECT
        CD_REG_AMB,
        COUNT(DISTINCT CD_RECCON_REC) AS QT_EVENTOS_NO_PERIODO,
        MIN(DT_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO_NO_PERIODO,
        MAX(DT_RECEBIMENTO) AS ULTIMO_RECEBIMENTO_NO_PERIODO,
        SUM(VL_RECEBIDO_FINANCEIRO) AS VL_RECEBIDO_FINANCEIRO_PERIODO,
        SUM(VL_RECEBIDO_BASE) AS VL_RECEBIDO_BASE_PERIODO,
        SUM(VL_ACRESCIMO) AS VL_ACRESCIMO_PERIODO,
        SUM(VL_GLOSA_RECEBIMENTO) AS VL_GLOSA_PERIODO
    FROM BASE
    WHERE DT_ESTORNO IS NULL
    GROUP BY CD_REG_AMB
),
REC_ACUMULADO AS (
    SELECT
        INF.CD_REG_AMB,
        COUNT(DISTINCT R.CD_RECCON_REC) AS QT_EVENTOS_ACUMULADOS,
        MIN(R.DT_RECEBIMENTO) AS PRIMEIRO_RECEBIMENTO,
        MAX(R.DT_RECEBIMENTO) AS ULTIMO_RECEBIMENTO,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO_ACUM,
        SUM(NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE_ACUM,
        SUM(NVL(V.VL_ACRESCIMO,0)) AS VL_ACRESCIMO_ACUM,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA_ACUM
    FROM CONTAS_PERIODO CP
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF ON INF.CD_REG_AMB = CP.CD_REG_AMB
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB
)
SELECT
    F.CD_PACIENTE,
    F.NM_PACIENTE,
    F.CD_ATENDIMENTO,
    F.CD_REG_AMB,
    F.CD_REMESSA,
    F.DT_ATENDIMENTO,
    F.DT_COMPETENCIA,
    F.VL_FATURADO,
    P.QT_EVENTOS_NO_PERIODO,
    P.PRIMEIRO_RECEBIMENTO_NO_PERIODO,
    P.ULTIMO_RECEBIMENTO_NO_PERIODO,
    P.VL_RECEBIDO_FINANCEIRO_PERIODO,
    P.VL_RECEBIDO_BASE_PERIODO,
    P.VL_ACRESCIMO_PERIODO,
    P.VL_GLOSA_PERIODO,
    A.QT_EVENTOS_ACUMULADOS,
    A.PRIMEIRO_RECEBIMENTO,
    A.ULTIMO_RECEBIMENTO,
    A.VL_RECEBIDO_FINANCEIRO_ACUM,
    A.VL_RECEBIDO_BASE_ACUM,
    A.VL_ACRESCIMO_ACUM,
    NVL(A.VL_GLOSA_ACUM,0) AS VL_GLOSA_ACUM,
    GREATEST(NVL(F.VL_FATURADO,0) - NVL(A.VL_RECEBIDO_BASE_ACUM,0),0) AS VL_SALDO_ESTIMADO,
    LEAST(
      GREATEST(NVL(F.VL_FATURADO,0) - NVL(A.VL_RECEBIDO_BASE_ACUM,0),0),
      NVL(A.VL_GLOSA_ACUM,0)
    ) AS VL_SALDO_GLOSADO,
    GREATEST(
      NVL(F.VL_FATURADO,0) - NVL(A.VL_RECEBIDO_BASE_ACUM,0) - NVL(A.VL_GLOSA_ACUM,0),
      0
    ) AS VL_SALDO_FINANCEIRO_ABERTO,
    CASE
      WHEN NVL(A.VL_RECEBIDO_BASE_ACUM,0) <= 0 THEN 'SEM_RECEBIMENTO'
      WHEN GREATEST(NVL(F.VL_FATURADO,0) - NVL(A.VL_RECEBIDO_BASE_ACUM,0),0) <= 0.01 THEN 'RECEBIDA'
      WHEN NVL(A.VL_GLOSA_ACUM,0) > 0.01
       AND GREATEST(NVL(F.VL_FATURADO,0) - NVL(A.VL_RECEBIDO_BASE_ACUM,0) - NVL(A.VL_GLOSA_ACUM,0),0) <= 0.01
        THEN 'RECEBIDA_COM_GLOSA'
      WHEN NVL(A.VL_GLOSA_ACUM,0) > 0.01 THEN 'PARCIALMENTE_RECEBIDA_COM_GLOSA'
      ELSE 'PARCIALMENTE_RECEBIDA'
    END AS STATUS_RECEBIMENTO,
    TRUNC(P.ULTIMO_RECEBIMENTO_NO_PERIODO) - TRUNC(F.DT_ATENDIMENTO) AS DIAS_ATENDIMENTO_RECEBIMENTO
FROM FAT_CONTA F
JOIN REC_PERIODO_CONTA P ON P.CD_REG_AMB = F.CD_REG_AMB
LEFT JOIN REC_ACUMULADO A ON A.CD_REG_AMB = F.CD_REG_AMB
ORDER BY P.ULTIMO_RECEBIMENTO_NO_PERIODO DESC, F.NM_PACIENTE, F.CD_REG_AMB
"""

PAGAMENTOS_AGING = PAGAMENTOS_BASE + r"""
, POR_CONTA_EVENTO AS (
    SELECT
        CD_RECCON_REC,
        CD_REG_AMB,
        MIN(DT_ATENDIMENTO) AS DT_ATENDIMENTO,
        MAX(DT_RECEBIMENTO) AS DT_RECEBIMENTO
    FROM BASE
    WHERE DT_ESTORNO IS NULL
      AND DT_ATENDIMENTO IS NOT NULL
    GROUP BY CD_RECCON_REC, CD_REG_AMB
),
PRAZOS AS (
    SELECT
        TRUNC(DT_RECEBIMENTO) - TRUNC(DT_ATENDIMENTO) AS DIAS
    FROM POR_CONTA_EVENTO
    WHERE DT_RECEBIMENTO >= DT_ATENDIMENTO
)
SELECT
    COUNT(*) AS QT_CONTA_EVENTO,
    ROUND(AVG(DIAS),1) AS DIAS_MEDIO,
    ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY DIAS),1) AS DIAS_P50,
    ROUND(PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY DIAS),1) AS DIAS_P90,
    SUM(CASE WHEN DIAS <= 30 THEN 1 ELSE 0 END) AS QT_ATE_30,
    SUM(CASE WHEN DIAS > 30 AND DIAS <= 60 THEN 1 ELSE 0 END) AS QT_31_60,
    SUM(CASE WHEN DIAS > 60 AND DIAS <= 90 THEN 1 ELSE 0 END) AS QT_61_90,
    SUM(CASE WHEN DIAS > 90 THEN 1 ELSE 0 END) AS QT_ACIMA_90,
    ROUND(SUM(CASE WHEN DIAS <= 30 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0) * 100,2) AS PCT_ATE_30,
    ROUND(SUM(CASE WHEN DIAS <= 60 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0) * 100,2) AS PCT_ATE_60,
    ROUND(SUM(CASE WHEN DIAS > 90 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0) * 100,2) AS PCT_ACIMA_90
FROM PRAZOS
"""

PAGAMENTO_ITENS_EVENTO = r"""
SELECT
    R.CD_RECCON_REC,
    R.DT_RECEBIMENTO,
    R.DT_ESTORNO,
    INF.CD_REMESSA,
    INF.CD_REG_AMB,
    INF.CD_NOTA_FISCAL,
    F.CD_ATENDIMENTO,
    A.CD_PACIENTE,
    COALESCE(P.NM_PACIENTE,F.NM_PACIENTE) AS NM_PACIENTE,
    F.DT_ATENDIMENTO,
    F.DT_COMPETENCIA,
    V.CD_ITFAT_NF,
    F.CD_PRO_FAT,
    F.VL_FATURADO,
    NVL(V.VL_RECEBIDO,0) AS VL_RECEBIDO_FINANCEIRO,
    NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0) AS VL_RECEBIDO_BASE,
    NVL(V.VL_ACRESCIMO,0) AS VL_ACRESCIMO,
    NVL(V.VL_DESCONTO,0) AS VL_DESCONTO,
    NVL(V.VL_IMPOSTO_RETIDO,0) AS VL_IMPOSTO_RETIDO,
    NVL(V.VL_GLOSA,0) AS VL_GLOSA_RECEBIMENTO
FROM DBAMV.RECCON_REC R
JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V ON V.CD_RECCON_REC = R.CD_RECCON_REC
JOIN DBAMV.ITFAT_NOTA_FISCAL INF ON INF.CD_ITFAT_NF = V.CD_ITFAT_NF
JOIN DBAMV.V_FNCP_ITEM_CONVENIO F ON F.CD_ITFAT_NF = V.CD_ITFAT_NF AND F.CD_CONVENIO = 11
LEFT JOIN DBAMV.ATENDIME A ON A.CD_ATENDIMENTO = F.CD_ATENDIMENTO
LEFT JOIN DBAMV.PACIENTE P ON P.CD_PACIENTE = A.CD_PACIENTE
WHERE R.CD_RECCON_REC = :cd_reccon_rec
  AND EXISTS (
      SELECT 1 FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
      WHERE AO.CD_ATENDIMENTO = F.CD_ATENDIMENTO
        AND AO.CD_CONVENIO = 11
  )
ORDER BY NM_PACIENTE, INF.CD_REG_AMB, V.CD_ITFAT_NF
"""

# Histórico financeiro das contas pertencentes à coorte de produção selecionada.
# O período seleciona CONTAS_ONCO por ITREG_AMB.DT_PRODUCAO.
# Depois disso, os recebimentos são pesquisados de forma acumulada, sem limitar
# RECCON_REC.DT_RECEBIMENTO ao período original.
HISTORICO_COMPETENCIAS = r"""
WITH ATEND_ONCO AS (
    SELECT DISTINCT AO.CD_ATENDIMENTO
    FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
    WHERE AO.CD_CONVENIO = 11
),
CONTAS_ONCO AS (
    SELECT DISTINCT
           IRA.CD_REG_AMB
    FROM DBAMV.ITREG_AMB IRA
    JOIN ATEND_ONCO AO
      ON AO.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
    WHERE IRA.CD_CONVENIO = 11
      AND IRA.DT_PRODUCAO >= :data_inicio
      AND IRA.DT_PRODUCAO < :data_fim + 1
),
FAT_COMP AS (
    SELECT
        INF.CD_REG_AMB,
        TRUNC(MIN(F.DT_COMPETENCIA), 'MM') AS DT_COMPETENCIA,
        SUM(NVL(F.VL_FATURADO,0)) AS VL_FATURADO
    FROM CONTAS_ONCO C
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF
      ON INF.CD_REG_AMB = C.CD_REG_AMB
    JOIN DBAMV.V_FNCP_ITEM_CONVENIO F
      ON F.CD_ITFAT_NF = INF.CD_ITFAT_NF
     AND F.CD_CONVENIO = 11
    GROUP BY INF.CD_REG_AMB
),
REC_TOTAL AS (
    SELECT
        INF.CD_REG_AMB,
        SUM(NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA
    FROM CONTAS_ONCO C
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF
      ON INF.CD_REG_AMB = C.CD_REG_AMB
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V
      ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R
      ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB
),
REC_MES AS (
    SELECT
        INF.CD_REG_AMB,
        TRUNC(R.DT_RECEBIMENTO, 'MM') AS MES_RECEBIMENTO,
        SUM(NVL(V.VL_RECEBIDO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(V.VL_RECEBIDO,0) - NVL(V.VL_ACRESCIMO,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(V.VL_GLOSA,0)) AS VL_GLOSA
    FROM CONTAS_ONCO C
    JOIN DBAMV.ITFAT_NOTA_FISCAL INF
      ON INF.CD_REG_AMB = C.CD_REG_AMB
    JOIN DBAMV.V_AJUSTES_RECEBIMENTO_DET V
      ON V.CD_ITFAT_NF = INF.CD_ITFAT_NF
    JOIN DBAMV.RECCON_REC R
      ON R.CD_RECCON_REC = V.CD_RECCON_REC
    WHERE R.DT_ESTORNO IS NULL
    GROUP BY INF.CD_REG_AMB, TRUNC(R.DT_RECEBIMENTO, 'MM')
),
COMP_RESUMO AS (
    SELECT
        TO_CHAR(F.DT_COMPETENCIA,'YYYY-MM') AS COMPETENCIA,
        COUNT(DISTINCT F.CD_REG_AMB) AS QT_CONTAS,
        SUM(F.VL_FATURADO) AS VL_FATURADO,
        SUM(NVL(T.VL_RECEBIDO_FINANCEIRO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(T.VL_RECEBIDO_BASE,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(T.VL_GLOSA,0)) AS VL_GLOSA,
        SUM(
            GREATEST(
                NVL(F.VL_FATURADO,0)
                - NVL(T.VL_RECEBIDO_BASE,0)
                - NVL(T.VL_GLOSA,0),
                0
            )
        ) AS VL_EM_ABERTO
    FROM FAT_COMP F
    LEFT JOIN REC_TOTAL T
      ON T.CD_REG_AMB = F.CD_REG_AMB
    GROUP BY F.DT_COMPETENCIA
),
EVENTOS AS (
    SELECT
        TO_CHAR(F.DT_COMPETENCIA,'YYYY-MM') AS COMPETENCIA,
        TO_CHAR(M.MES_RECEBIMENTO,'YYYY-MM') AS MES_RECEBIMENTO,
        SUM(NVL(M.VL_RECEBIDO_FINANCEIRO,0)) AS VL_RECEBIDO_FINANCEIRO,
        SUM(NVL(M.VL_RECEBIDO_BASE,0)) AS VL_RECEBIDO_BASE,
        SUM(NVL(M.VL_GLOSA,0)) AS VL_GLOSA
    FROM FAT_COMP F
    JOIN REC_MES M
      ON M.CD_REG_AMB = F.CD_REG_AMB
    GROUP BY F.DT_COMPETENCIA, M.MES_RECEBIMENTO
)
SELECT
    C.COMPETENCIA,
    C.QT_CONTAS,
    C.VL_FATURADO,
    C.VL_RECEBIDO_FINANCEIRO,
    C.VL_RECEBIDO_BASE,
    C.VL_GLOSA,
    C.VL_EM_ABERTO,
    E.MES_RECEBIMENTO,
    NVL(E.VL_RECEBIDO_FINANCEIRO,0) AS VL_RECEBIDO_MES,
    NVL(E.VL_RECEBIDO_BASE,0) AS VL_RECEBIDO_BASE_MES,
    NVL(E.VL_GLOSA,0) AS VL_GLOSA_MES
FROM COMP_RESUMO C
LEFT JOIN EVENTOS E
  ON E.COMPETENCIA = C.COMPETENCIA
ORDER BY C.COMPETENCIA, E.MES_RECEBIMENTO
"""
