PRODUTOS = """
WITH ONCO_ATEND AS (
    SELECT DISTINCT AO.CD_ATENDIMENTO
    FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
    WHERE AO.CD_CONVENIO = 11
),
MOV_ONCO AS (
    SELECT
        IME.CD_PRODUTO,
        COUNT(*) AS MOV_ONCO
    FROM DBAMV.ITREG_AMB IRA
    JOIN ONCO_ATEND OA
      ON OA.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
    JOIN DBAMV.ITMVTO_ESTOQUE IME
      ON IME.CD_ITMVTO_ESTOQUE = IRA.CD_ITMVTO
    WHERE IRA.CD_CONVENIO = 11
      AND IRA.CD_ITMVTO IS NOT NULL
      AND IRA.DT_PRODUCAO >= :data_inicio
      AND IRA.DT_PRODUCAO < :data_fim + 1
    GROUP BY IME.CD_PRODUTO
),
MOV_TOTAL AS (
    SELECT
        IME.CD_PRODUTO,
        COUNT(*) AS MOV_TOTAL
    FROM DBAMV.ITREG_AMB IRA
    JOIN DBAMV.ITMVTO_ESTOQUE IME
      ON IME.CD_ITMVTO_ESTOQUE = IRA.CD_ITMVTO
    JOIN MOV_ONCO MO
      ON MO.CD_PRODUTO = IME.CD_PRODUTO
    WHERE IRA.CD_ITMVTO IS NOT NULL
      AND IRA.DT_PRODUCAO >= :data_inicio
      AND IRA.DT_PRODUCAO < :data_fim + 1
    GROUP BY IME.CD_PRODUTO
)
SELECT
    P.CD_PRODUTO,
    P.DS_PRODUTO,
    P.SN_MEDICAMENTO,
    MO.MOV_ONCO,
    MT.MOV_TOTAL,
    ROUND(100 * MO.MOV_ONCO / NULLIF(MT.MOV_TOTAL,0), 2) AS PCT_ONCO,
    CASE
        WHEN 100 * MO.MOV_ONCO / NULLIF(MT.MOV_TOTAL,0) >= 95 THEN 'ONCO_100PCT_OBSERVADO'
        WHEN 100 * MO.MOV_ONCO / NULLIF(MT.MOV_TOTAL,0) >= 80 THEN 'ONCO_PREDOMINANTE'
        WHEN 100 * MO.MOV_ONCO / NULLIF(MT.MOV_TOTAL,0) >= 50 THEN 'ONCO_ASSOCIADO'
        WHEN 100 * MO.MOV_ONCO / NULLIF(MT.MOV_TOTAL,0) >= 20 THEN 'USO_COMPARTILHADO'
        ELSE 'USO_GERAL'
    END AS CLASSIFICACAO,
    CASE
        WHEN MO.MOV_ONCO >= 20 THEN 'ALTA'
        WHEN MO.MOV_ONCO >= 5 THEN 'MEDIA'
        ELSE 'BAIXA'
    END AS CONFIANCA
FROM MOV_ONCO MO
JOIN MOV_TOTAL MT ON MT.CD_PRODUTO = MO.CD_PRODUTO
JOIN DBAMV.PRODUTO P ON P.CD_PRODUTO = MO.CD_PRODUTO
ORDER BY PCT_ONCO DESC, MO.MOV_ONCO DESC
"""
