RESUMO = """
WITH ATEND_ONCO AS (
    SELECT DISTINCT AO.CD_ATENDIMENTO
    FROM DBAMV.AGENDAMENTO_ONCOLOGICO AO
    WHERE AO.CD_CONVENIO = 11
),
CONTAS AS (
    SELECT DISTINCT
           IRA.CD_ATENDIMENTO,
           IRA.CD_REG_AMB
    FROM DBAMV.ITREG_AMB IRA
    JOIN ATEND_ONCO AO
      ON AO.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
    WHERE IRA.CD_CONVENIO = 11
      AND IRA.DT_PRODUCAO >= :data_inicio
      AND IRA.DT_PRODUCAO < :data_fim + 1
),
PRODUTOS AS (
    SELECT DISTINCT IME.CD_PRODUTO
    FROM DBAMV.ITREG_AMB IRA
    JOIN CONTAS C
      ON C.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
     AND C.CD_REG_AMB = IRA.CD_REG_AMB
    JOIN DBAMV.ITMVTO_ESTOQUE IME
      ON IME.CD_ITMVTO_ESTOQUE = IRA.CD_ITMVTO
    WHERE IRA.CD_ITMVTO IS NOT NULL
)
SELECT
    (SELECT COUNT(DISTINCT CD_ATENDIMENTO) FROM CONTAS) AS ATENDIMENTOS_COM_FATURAMENTO,
    (SELECT COUNT(DISTINCT CD_REG_AMB) FROM CONTAS) AS CONTAS_ONCO,
    (SELECT COUNT(*) FROM PRODUTOS) AS PRODUTOS_DISTINTOS
FROM DUAL
"""
