SCHEMA_CAPABILITIES = r"""
SELECT
    SUM(CASE WHEN TABLE_NAME='ATENDIME' AND COLUMN_NAME='CD_ATENDIMENTO' THEN 1 ELSE 0 END) AS ATENDIME_CD_ATENDIMENTO,
    SUM(CASE WHEN TABLE_NAME='ATENDIME' AND COLUMN_NAME='CD_PACIENTE' THEN 1 ELSE 0 END) AS ATENDIME_CD_PACIENTE,
    SUM(CASE WHEN TABLE_NAME='PACIENTE' AND COLUMN_NAME='CD_PACIENTE' THEN 1 ELSE 0 END) AS PACIENTE_CD_PACIENTE,
    SUM(CASE WHEN TABLE_NAME='PACIENTE' AND COLUMN_NAME='NM_PACIENTE' THEN 1 ELSE 0 END) AS PACIENTE_NM_PACIENTE,
    SUM(CASE WHEN TABLE_NAME='FA_CUSTO_ATENDIMENTO' AND COLUMN_NAME='CD_ATENDIMENTO' THEN 1 ELSE 0 END) AS CUSTO_CD_ATENDIMENTO,
    SUM(CASE WHEN TABLE_NAME='FA_CUSTO_ATENDIMENTO' AND COLUMN_NAME='VL_CUSTO_MEDICAMENTO' THEN 1 ELSE 0 END) AS CUSTO_VL_MEDICAMENTO,
    SUM(CASE WHEN TABLE_NAME='RECCON_REC' AND COLUMN_NAME='CD_RECCON_REC' THEN 1 ELSE 0 END) AS REC_CD_RECCON_REC,
    SUM(CASE WHEN TABLE_NAME='RECCON_REC' AND COLUMN_NAME='DT_RECEBIMENTO' THEN 1 ELSE 0 END) AS REC_DT_RECEBIMENTO,
    SUM(CASE WHEN TABLE_NAME='RECCON_REC' AND COLUMN_NAME='DT_ESTORNO' THEN 1 ELSE 0 END) AS REC_DT_ESTORNO,
    SUM(CASE WHEN TABLE_NAME='V_AJUSTES_RECEBIMENTO_DET' AND COLUMN_NAME='CD_ITFAT_NF' THEN 1 ELSE 0 END) AS AJ_CD_ITFAT_NF,
    SUM(CASE WHEN TABLE_NAME='V_AJUSTES_RECEBIMENTO_DET' AND COLUMN_NAME='CD_RECCON_REC' THEN 1 ELSE 0 END) AS AJ_CD_RECCON_REC,
    SUM(CASE WHEN TABLE_NAME='V_AJUSTES_RECEBIMENTO_DET' AND COLUMN_NAME='VL_RECEBIDO' THEN 1 ELSE 0 END) AS AJ_VL_RECEBIDO,
    SUM(CASE WHEN TABLE_NAME='V_AJUSTES_RECEBIMENTO_DET' AND COLUMN_NAME='VL_ACRESCIMO' THEN 1 ELSE 0 END) AS AJ_VL_ACRESCIMO,
    SUM(CASE WHEN TABLE_NAME='ITFAT_NOTA_FISCAL' AND COLUMN_NAME='CD_REG_AMB' THEN 1 ELSE 0 END) AS NF_CD_REG_AMB,
    SUM(CASE WHEN TABLE_NAME='ITFAT_NOTA_FISCAL' AND COLUMN_NAME='CD_REMESSA' THEN 1 ELSE 0 END) AS NF_CD_REMESSA,
    SUM(CASE WHEN TABLE_NAME='V_FNCP_ITEM_CONVENIO' AND COLUMN_NAME='CD_ITFAT_NF' THEN 1 ELSE 0 END) AS FNCP_CD_ITFAT_NF,
    SUM(CASE WHEN TABLE_NAME='V_FNCP_ITEM_CONVENIO' AND COLUMN_NAME='DT_COMPETENCIA' THEN 1 ELSE 0 END) AS FNCP_DT_COMPETENCIA,
    SUM(CASE WHEN TABLE_NAME='V_FNCP_ITEM_CONVENIO' AND COLUMN_NAME='VL_FATURADO' THEN 1 ELSE 0 END) AS FNCP_VL_FATURADO
FROM ALL_TAB_COLUMNS
WHERE OWNER='DBAMV'
  AND TABLE_NAME IN (
      'ATENDIME','PACIENTE','FA_CUSTO_ATENDIMENTO','RECCON_REC',
      'V_AJUSTES_RECEBIMENTO_DET','ITFAT_NOTA_FISCAL','V_FNCP_ITEM_CONVENIO'
  )
"""
